# @package _global_

defaults:
  - /agent/contrib/erl-ori
  - _self_

total_episodes: 100000

batch_size: 256 # 128 in ERL
tau: 0.005 # 0.001 in ERL

pop_size: 10
num_elites: 4 # 3 in ERL
episodes_for_fitness: 1 # must be devided by num_envs
rollout_episodes: 1 # must be devided by num_envs

rl_updates_frac_per_iter: 1.0
rl_injection_interval: 1
