# @package _global_

defaults:
  - /agent/ec/ars
  - _self_

num_iters: 2000

pop_size: 2
num_elites: 1
lr: 0.02
noise_std: 0.01

agent_network:
  actor_hidden_layer_sizes: []
  use_bias: false

wandb:
  tags: ["ori"]
