# @package _global_

defaults:
  - /agent/contrib/td3-v2
  - _self_

num_envs: 1
normalize_obs: false
rollout_length: 1
discount: 0.99
total_timesteps: 5000000
fold_iters: 16384

num_eval_envs: 16
eval_episodes: 16 # should be divided by num_eval_envs
eval_interval: 16384 # unit: num of iterations

checkpoint:
  save_interval_steps: 163840
