repos:
  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.13.2
  #   hooks:
  #     - id: isort
  #       name: isort (python)

  # - repo: https://github.com/psf/black
  #   rev: 24.4.2
  #   hooks:
  #     - id: black
  #       name: "Code formatter"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      # # Run the linter.
      - id: ruff
        args: [ '--fix' ]
      # Run the formatter.
      - id: ruff-format


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        name: "End of file fixer"
      - id: mixed-line-ending
        name: "Mixed line ending fixer"
      - id: check-yaml
        name: "Yaml checker"
        args: [ '--unsafe' ]
        files: ^configs/.*\.ya?ml$
      - id: trailing-whitespace
        name: "Trailing whitespace fixer"
      - id: debug-statements
        name: "Debug imports and breakpoints checker"
      - id: requirements-txt-fixer
        name: "Requirements txt fixer"
        files: requirements/requirements.*\.txt$
