# @package _global_

defaults:
  - /agent/sac
  - _self_

num_envs: 64
normalize_obs: true
rollout_length: 1
discount: 0.99
total_timesteps: 10000000
fold_iters: 512

reward_scale: 1.0 # Note: unlike cfg in brax, we don't change reward_scale
adaptive_alpha: true
alpha: 1.0 # used as initial alpha value if adaptive_alpha is true

num_updates_per_iter: 4 # each update contains 1 actor update & actor_update_interval critic updates


num_eval_envs: 16
eval_episodes: 16 # should be divided by num_eval_envs
eval_interval: 512 # unit: num of iterations

checkpoint:
  save_interval_steps: 5120

wandb:
  tags: ["batch1"]
