# @package _global_

defaults:
  - /agent/sac
  - _self_


total_timesteps: 2048000 # 2*2048*500, same as PBT-SAC
fold_iters: 8192

num_eval_envs: 128
eval_episodes: 128
eval_interval: 8192

reward_scale: 1.0 # Note: unlike cfg in brax, we don"t change reward_scale
adaptive_alpha: true
alpha: 1.0 # used as initial alpha value if adaptive_alpha is true


tags: ["paramsac"]
