# @package _global_

workflow_cls: evorl.algorithms.ec.so.evox_openes.OpenESWorkflow

pop_size: 128
num_iters: 1000

noise_std: 0.1
optimizer:
  lr: 0.01

num_envs: 16
episodes: 16 # episodes per individual for fitness

num_eval_envs: 128
eval_episodes: 128
eval_interval: 10

discount: 1.0

agent_network:
  actor_hidden_layer_sizes: [16, 16]
  norm_layer_type: 'none'
