# @package _global_

defaults:
  - /agent/meta@target_workflow: paramsac
  - _self_

workflow_cls: evorl.algorithms.meta.pbt_sac.pbt_param_sac.PBTParamSACWorkflow

pop_size: 8

parallel_train: true
parallel_eval: true
workflow_steps_per_iter: 5

warmup_steps: 5 # warmup_iters = warmup_steps // workflow_steps_per_iter

num_iters: 500

# PBT hyperparameters:
bottom_ratio: 0.2
top_ratio: 0.2

perturb_factor:
  actor_loss_weight: 0.2
  critic_loss_weight: 0.2
  alpha_loss_weight: 0.2
  discount_g: 0.2
  target_entropy_h: 0.2

search_space:
  actor_loss_weight:
    low: 0.01
    high: 10
  critic_loss_weight:
    low: 0.01
    high: 10
  alpha_loss_weight:
    low: -1
    high: -1e-5
  discount_g: # discount=1-exp(h), [0.86466, 0.99999]
    low: -12
    high: -2
  target_entropy_h:
    low: 0.1
    high: 10

target_workflow:
  num_eval_envs: 16
  eval_episodes: 16

checkpoint:
  save_interval_steps: 50
