# @package _global_

defaults:
  - /agent/pbt-paramsac
  - _self_

pop_size: 128

parallel_train: true
parallel_eval: true
workflow_steps_per_iter: 2048

warmup_steps: 2048

num_iters: 500

checkpoint:
  save_interval_steps: 50
