# @package _global_

defaults:
  - /agent/pbt-paramppo
  - _self_

pop_size: 128

parallel_train: true
parallel_eval: true
workflow_steps_per_iter: 64

warmup_steps: 256 # 4 warmup iters

num_iters: 500

checkpoint:
  save_interval_steps: 50
