# @package _global_

defaults:
  - /agent/td3
  - _self_

workflow_cls: evorl.algorithms.contrib.td3_layer_norm.TD3LayerNormWorkflow

agent_network:
  static_layer_norm: true
  critic_hidden_layer_sizes: [256, 256]
  actor_hidden_layer_sizes: [256, 256]
