# @package _global_

defaults:
  - locomotion_default
  - _self_

# used for env: "Go1Backflip"

discount: 0.95
total_timesteps: 200_000_000

agent_network:
  actor_hidden_layer_sizes: [512, 256, 128]
  critic_hidden_layer_sizes: [512, 256, 128] # Note: we use state instead of privileged_state in playground as input
