# @package _global_

workflow_cls: evorl.agents.a2c.A2CWorkflow

num_envs: 8

normalize_obs: true
rollout_length: 50 # train_batch_size = rollout_length * num_envs = 256
gae_lambda: 0.95
discount: 0.99

total_timesteps: 1000000

num_eval_envs: 8
eval_interval: 50
eval_episodes: 16 # should be divided by num_eval_envs

optimizer:
  lr: 0.0001
  grad_clip_norm: 10.0 # set 0 or none to turn-off
  loss_weights:
    actor_loss: 1.0
    critic_loss: 0.5
    actor_entropy_loss: -0.01

agent_network:
  continuous_action: true
  actor_hidden_layer_sizes: [256, 256]
  critic_hidden_layer_sizes: [256, 256]
