# @package _global_

workflow_cls: evorl.algorithms.erl.cemrl.CEMRLWorkflow

num_envs: 1
normalize_obs: false
rollout_length: 2
discount: 0.99
total_timesteps: 5000000

num_eval_envs: 16
eval_episodes: 16 # should be divided by num_eval_envs
eval_interval: 8192 # unit: num of RL updates

random_timesteps: 25600 # steps filled into the replay buffer
learning_start_timesteps: 25600 # steps before training starts
batch_size: 256
replay_buffer_capacity: 1000000

tau: 0.005 # soft update rate
exploration_epsilon: 0.1
policy_noise: 0.2
clip_policy_noise: 0.5
actor_update_interval: 2
num_updates_per_iter: 1 # #updates per rollout, usually use: num_envs * rollout_length // actor_update_interval

# cemrl only hyperparams:
pop_size: 32
num_learning_offspring: 16 # number of offspring to learn from RL(TD3)

cemrl_update_interval: 8192 # unit: num of RL updates per CEMRL iteration
fitness_with_exploration: true



loss_weights:
  actor_loss: 1.0
  critic_loss: 0.5

optimizer:
  lr: 0.0003
  grad_clip_norm: 0 # set 0 or none to turn-off

agent_network:
  critic_hidden_layer_sizes: [256, 256]
  actor_hidden_layer_sizes: [256, 256]

save_replay_buffer: true
