# @package _global_

pop_size: 128
num_iters: 1000

parallel_envs: 16
eval_episodes: 16

metric_names: ['reward_forward', 'reward_ctrl']

agent_network:
  actor_hidden_layer_sizes: [] # linear network
  lb: -10
  ub: 10