# @package _global_

pop_size: 7
num_iters: 100

parallel_envs: 5
eval_episodes: 5

metric_names: ['reward_forward', 'reward_ctrl']

agent_network:
  actor_hidden_layer_sizes: [] # linear network
  lb: -10
  ub: 10