# @package _global_

defaults:
  - _self_
  - override target_workflow@target_workflow: ../ppo

workflow_cls: evorl.agents.meta.pbt.PBTWorkflow

pop_size: 8

parallel_train: true
parallel_eval: true
per_iter_workflow_steps: 1

# PBT hyperparameters:
bottom_ratio: 0.2
top_ratio: 0.2

perturb_factor:
  lr: 0.2

search_space:
  lr:
    low: 1e-5
    high: 1e-3

target_workflow:
  num_eval_envs: 4
  eval_episodes: 16
