# @package _global_

# Note:
# this config is similar as pop_td3.yaml
# except the rollout is based on episodes + use shared critic network.

defaults:
  - /agent/contrib/cemrl-nocem
  - _self_

total_episodes: 100000

actor_update_interval: 1

warmup_iters: 10 # steps that only learn by CEM

pop_size: 10
num_learning_offspring: 10

num_elites: 5
diagonal_variance:
  init: 1e-2
  final: 1e-5
  decay: 0.05

fitness_with_exploration: true
episodes_for_fitness: 1 # must be devided by num_envs
num_rl_updates_per_iter: 5 # num of RL updates per iter

num_eval_envs: 128
eval_episodes: 128 # should be divided by num_eval_envs
eval_interval: 50
