# @package _global_

defaults:
  - /agent/contrib/cemrl-ori
  - _self_

total_episodes: 20000

actor_update_interval: 1 # not needed since we apply it over #num_learning_offspring actors

warmup_iters: 10 # steps that only learn by CEM

pop_size: 10
num_learning_offspring: 5

num_elites: 5
cov_eps:
  init: 1e-2
  final: 1e-5
  decay: 0.05

fitness_with_exploration: false
episodes_for_fitness: 1 # must be devided by num_envs
rl_updates_frac: 1.0

num_eval_envs: 128
eval_episodes: 128 # should be divided by num_eval_envs
eval_interval: 10

wandb:
  tags: ["fastpbrl"]
